### ISSUE TITLE
Voice not Corresponding with the Text

### ISSUE THREAD

**Issue by ItaloKnox** [07th-mod/onikakushi#107]
_From @mfdsrax2 on March 5, 2018 6:3_

I just started playing Onikakushi (JP version) and downloaded Voice and Graphics Patch here. But found that some voices are not linked with the corresponding text. The voice for the marked text appears in a later dialog.

I played this game for less than half an hour and found quite a lot of voices unsyncing. I believe that must be a big issue. Will someone look into this?
![20180304214441_1](https://user-images.githubusercontent.com/13324717/36959570-9c49cef4-1ff7-11e8-907e-28220e03ee17.jpg)
![20180304214732_1](https://user-images.githubusercontent.com/13324717/36959571-9c600070-1ff7-11e8-9263-ff8180e61b5f.jpg)

_Copied from original issue: 07th-mod/guide#22_

**Comment by ItaloKnox** [comment]
_From @mfdsrax2 on March 8, 2018 2:51_

This triangle is really of low resolution with aliasing. Do you have plans for a high-res replacement?
![inked20180307182844_1_li](https://user-images.githubusercontent.com/13324717/37130437-44cdb454-2238-11e8-84de-d3c43b4e8c42.jpg)

**Comment by ItaloKnox** [comment]
Oh, that's a really handy tool. Let's see if it works.

**Comment by mfdsrax2** [comment]
This dialog was split into 2 parts. I don't know if it's intentional. Not many dialogs look like this.
![inked20180327011318_1_li](https://user-images.githubusercontent.com/13324717/37956602-a66a76a2-3160-11e8-8ce4-ff57c18525ca.jpg)
![1](https://user-images.githubusercontent.com/13324717/37956639-bd7fd71a-3160-11e8-8e86-a156a42d1cbf.PNG)

The actual voice is 「もうすぐここでお祭りがあるんだがら。」
![inked20180327011713_1_li](https://user-images.githubusercontent.com/13324717/37956745-084637f8-3161-11e8-9e64-c0f7b25fd922.jpg)

An end quotation mark is missing.
![inked20180327012321_1_li](https://user-images.githubusercontent.com/13324717/37956777-23eea7a6-3161-11e8-89b6-73f2490bb4e6.jpg)

Text split again.
![20180327012729_1](https://user-images.githubusercontent.com/13324717/37956930-845dd382-3161-11e8-9b89-61302fd3eedb.jpg)

There is no voice with this text. But the Japanese name for _Satoko_ is 『沙都子』throughout the game.
![inked20180327012846_1_li](https://user-images.githubusercontent.com/13324717/37956970-9d1d3cdc-3161-11e8-8af3-84b761acae5a.jpg)

I didn't hear this voice clear and there is any way to repeat it without reloading, but I'm pretty sure it's not the same as the text shows. Maybe this dialog is censored. 
![20180327013417_1](https://user-images.githubusercontent.com/13324717/37957073-e5af3874-3161-11e8-95b5-d73eeaf0002a.jpg)

That's all the problems I found in Ch. 2. I didn't read TIPS yet but apparently it's much better than Ch. 1.

**Comment by mfdsrax2** [comment]
Oh sorry maybe I should open a new issue.
