### ISSUE TITLE
Opening video does not play under Proton (Steam Deck)

### ISSUE THREAD

**Issue by BrandoNarv** [07th-mod/onikakushi#217]
After following the recommended method of using Proton to run Higurashi due to issues from the Native Linux version on Steam Deck, the game runs awesome! The only problem though is that for whatever reason, the opening just does not play at all. I have tried both the Enabled flag and the Launch + In Game flag on the mod menu but the opening does not play on start up nor after the opening scene. I have tested it on both the latest Proton version (9.0-2) and Experimental but both do not solve the issue at all. While it may be an issue on all of the games (and I haven't checked yet if it affects all the games), I am putting it here since I am experiencing it on Onikakushi.

**Comment by drojf** [comment]
I investigated this issue (another user reported the same issue on Ch.8).

It's a problem with our mod - you can fix it by:
- Deleting the .mp4 file under `Higurashi When They Cry Modded\HigurashiEp01_Data\StreamingAssets\movies\mv01.mp4`. This will force the game to play the `.ogv` file instead.
- Open the game folder (via steam), then navigate to HigurashiEp08_Data\Managed, then overwrite the existing `Assembly-CSharp.dll` file with this one: [Assembly-CSharp_onikakushi_ch1_fix_proton_video_2024-08-23.zip](https://github.com/user-attachments/files/16729106/Assembly-CSharp_onikakushi_ch1_fix_proton_video_2024-08-23.zip)
- Wait until I do a proper release which fixes this issue, then update the mod

I think this issue affects ch.1-8

----

I'm pretty sure this issue was introduced when we updated all the archives and ship both the windows and linux video files together, so the engine would try to play the windows video file under Wine.

**Comment by drojf** [comment]
I just re-tested on a fresh Proton Experimental install of Ch.1 after applying these fixes, and found that I forgot to merge my changes for Ch.1.

Then I fixed that, and tested again, and video playback worked, so I think this issue can be closed now.

Please reopen this issue if you still have problems, even after updating your game
