### ISSUE TITLE
Missing voice in tip 16

### ISSUE THREAD

**Issue by enumag** [07th-mod/onikakushi#23]
I think a voice is missing for [this line](https://github.com/higurashi-mod/onikakushi/blob/854c292dadf5d1df40abac2971d7bc469d0aec6f/Update/onik_tips_16.txt#L262-L263). The previous line does not have ending qoutes and its voice file seems too short to contain both sentenses.

**Comment by ItaloKnox** [comment]
That's a little awkward because both lines doesn't match with the japanese script. Maybe that's the problem here? They pretty much have the same translation, excluding the fact that the PC script is a lot longer.

I don't think it looks right to change the translation for this one, dunno about how to proceed.

S20/00/443200036	「他には、……そうじゃな。脳障害によって精神に異常を発生する状態じゃな」
OutputLine(NULL, "「急性器質性精神病、っちゅうのを知っとるかの？",
OutputLine(NULL, "　早い話が、脳障害によって精神がとんちんかんになる状態じゃな。",

S20/00/443200037	「これは薬物中毒でも起こるが、脳の外傷や一部の病気なんかでも起こる」
OutputLine(NULL, "これは薬物中毒でも起こるが、脳の外傷や脳炎、脳卒中、脳腫瘍なんかでも起こる。」",
