### ISSUE TITLE
CGs with capital letters don't load under Linux & Mac

### ISSUE THREAD

**Issue by GiantBlargg** [07th-mod/onikakushi#65]
The engine seems to convert all capital letters in filenames to lowercase ones. This makes no difference when running on Windows as filenames are case-insensitive. Under Linux, however filenames are case sensitive. So when the engine requests a file it finds nothing. If the CG is drawn with `DrawBustshot` the scene will play out as normal just without that CG. If drawn with `DrawBustshotWithFiltering` the game will hang.

**Comment by ItaloKnox** [comment]
Hmmm, I'm not sure if I get it. As you pointed out, Unix-based systems will have trouble because of their enforced case-sensitive filesystem, however we fixed this issue a long time ago.

But anyway, both DrawBustshot and DrawBustshotWithFiltering will always call the same files from the same folder, unless I'm confusing things here.

```	DrawBustshotWithFiltering( 1, "re_se_de_a1", "c", 1, -160, 0, FALSE, 0, 0, 0, 0, 0, 0, 300, TRUE );
	DrawBustshot( 3, "me_se_fu_a2", 160, 0, 0, FALSE, 0, 0, 0, 0, 0, 0, 0, 20, 200, TRUE );	
```

Both are calling files from the same folder (/HigurashiEp01_Data/StreamingAssets/CGAlt). In this case, I'm pretty positive this is not an issue with this patch.
If DrawBustshotWithFiltering is actually converting the path to lowercase, then that's an issue with the engine, not with the patch. Most likely you should seek [Doddler's help on the Steam forums](http://steamcommunity.com/app/310360/discussions/).

Perhaps I'm completely misreading the issue here, so I hope you can elaborate a little more.

**Comment by GiantBlargg** [comment]
What I was trying to say is that both functions will try (and fail) to load the same file, but how they deal with that failure is different.

Sorry, looking over it again it seems the problem is with the graphics packs, I kinda forgot that they were downloaded separately. The specific problem I was having was with the teacher sprites (Tie_def, Tie_Niramu). Is there any way I can contact the maintainer of those packs?

**Comment by ItaloKnox** [comment]
Now that makes more sense. The creator of the graphics packs usually hangs out at the Steam forums I linked above. We call him GuraMan, if I recall correctly his username is pretty much the same thing. Just search for the graphics mod thread, you'll find him.

**Comment by GiantBlargg** [comment]
Oh sorry, I was going to come back and close this if this ever got resolved but the person making the packs never got back to me.

For anyone else who stumbles upon this, you can run `find . -depth -exec rename 's/(.*)\/([^\/]*)/$1\/\L$2/' {} \;` inside the CGAlt folder to fix all the filenames.

**Comment by ItaloKnox** [comment]
Good to know! I'm setting up a wiki for the patch, so this is will help. 👍
