### ISSUE TITLE
Text out of the box

### ISSUE THREAD

**Issue by pamput** [07th-mod/onikakushi#66]
It seems that the box containing the text is too small:

![image](https://cloud.githubusercontent.com/assets/3295190/18006155/2900039e-6b96-11e6-80dd-ab830733cb5e.png)

I have downloaded your latest patch.

**Comment by ItaloKnox** [comment]
Looks like you are not running the latest graphics patch? Try downloading [this graphics patch](http://www.mediafire.com/download/3ayecfk2eta9kk2/Higurashi+Steam+-+Full+PS3+Mod+1.5+%5BWide+screen+support%5D.rar) and then applying our patch again overwriting it.

**Comment by pamput** [comment]
Nope, this is exactly the graphic pack I already have. 

> and then applying our patch again overwriting it.

Not sure what you mean. If by `it` you mean the graphic pack, I should point out that your patch doesn't contain any graphic asset. Otherwise, if you simply mean 're-apply the patch' the straight forward way, I already tried it. I also tried to delete the `*.md` files to force a recompilation, without success (also, I don't think the scripts are actually stretching the asset in any way :\ )

I have also tried both the `steam` and `ps3` packs (wide screen version). Both have the same `windo_filter.png` asset. I have created my own version of the image that fits the text nicely. I can create a PR if you want.

**Comment by ItaloKnox** [comment]
The issue here is that your game is not rendering in widescreen. It's supposed to look like this:

![](https://i.mugi.io/MkZs.jpg)

That's why the textbox is not fitting the text correctly. There are only two possibilities here:

1. your game is running the old compiled init.mg file instead of the patched one (unlikely, but did you clean **both** CompiledScripts folders?)
2. you are actually running the wrong graphics patch (try checking your CGAlt folder, pretty much all backgrounds should be 1280x720)

**Comment by pamput** [comment]
Ok, not sure what mess I have done, but now it seems better. It's rendering in widescreen at least :D

My only concern is the menu, is it rendering correctly?

![image](https://cloud.githubusercontent.com/assets/3295190/18010098/059d04ea-6ba7-11e6-9dd1-2e372aa0cc69.png)

**Comment by ItaloKnox** [comment]
I guess so. We don't have control over certain screen elements, I guess this is one of them.
Usually I leave mine hidden, so they were never a bother.
