### ISSUE TITLE
Wrong translation?

### ISSUE THREAD

**Issue by enumag** [07th-mod/onikakushi#80]
@ItaloKnox This [line](https://github.com/07th-mod/onikakushi/blob/586033d48ec132ab37a3953787529fac3b42f4b3/Update/onik_004.txt#L754-L756) seems to have a wrong english translation. It seems too long and doesn't match the short voice line. Can you check it and provide a better translation?

**Comment by ItaloKnox** [comment]
The line is correct but seems long because in japanese they are talking about "that", which makes not much sense in english since "that" is "that". I think you can get what I'm talking about?

You can shorten it if you want as long as the meaning of the original text doesn't change. The translator is a pretty trustworthy guy, I think he just made it a little too long.

**Comment by enumag** [comment]
Oh. Yeah, I understand it now. Do you have a suggestion for shorter version or would you recommend leaving it as is?

**Comment by ItaloKnox** [comment]
Hmm, I actually think we should shorten it.

``"'That' means a person, thing, idea or event related to the context.``

Or something like that? I think "action" is already implied by "event", so maybe brushing it up a bit will make it look nice.

**Comment by enumag** [comment]
Possibly like this? I'm thinking of dropping "idea" too.

```
"'That' means a previously indicated person, thing, idea or event."
```

**Comment by ItaloKnox** [comment]
Looks great! I would go with that.

**Comment by enumag** [comment]
Fixed, thank you!
