### ISSUE TITLE
Suggestion for censored texts.

### ISSUE THREAD

**Issue by P-Chang** [07th-mod/onikakushi#85]
First, I'm not native English speaker, Sorry for my broken English.
And thank you for great mod and hard works.

It is confusing that original and censored text are in the same scene.
This time is not my first experience, so I can complement in my mind. But new player may be confuse.

Original and console are based on same story but both storyline is bit different.
Early 3 episodes have prequel in console. And these have bit different scenes.

Console dev changed texts of serious scene for violence and political correctness.
They changed texts of comedy scene for sexual and copyright issue.
And deleted texts have many background of character and story.

Cutting and replace is not good way.
It cause contradictionand and misunderstanding in another scene, chapter, episode.
Console devs changed ton of non-voiced texts for censorship 
and change of game system. Replacing all is colossal work.
Translate it is too difficult. It needs many knowledge of 
Japanese culture(Anime, Game, Traditional, Political, Historical, etc)

Voice and text is bit different and some texts don't have voices are not unusual in Japanese games.

I suggest marking instead of cutting or replacing.

Example:
*: it was changed in console version
-: it was deleted in console version
+: it was added in console version
#: it was changed to console version text for some reason(both language)
%: it was changed to console version text for some reason(Japanese only)

I'm not good in coding. if these character have problem, change it.

1,Add comment out for information of different voice
2.Add mark the top of Japanese text line.
3.Make new blank OGG file that have same name for someone who want to delete the different voice(optional file)

//「......じゃあそろそろいい＠　この拷問はね、とてもシンプル＠左手の小指の先端の節に釘を打つ＠順に親指まで打ったらまた小指に戻って、今度は真ん中の節に釘を打つ＠...この調子で１５本の釘で左手を打ちつける＠それが終わったら次は右手＠......それが終わったら次は、............まだ意識があったら教えるね＠指先って、たくさんの神経が集まってるから、圭ちゃんが想像するよりもはるかに痛いよ＠...両手３０本を打ち終える前に、失神しちゃう人もいるそうだから...。￥
// some voice is not include 「......じゃあそろそろいい？　この拷問はね、とてもシンプル」
	PlaySE(4, "s02/03/130300673", 128, 64);
	OutputLine(NULL, "*「……じゃあそろそろいい？",
		   NULL, "\"...Can I start now, then?", Line_WaitForInput);
	PlaySE(4, "S02/03/130300674", 128, 64);
	OutputLine(NULL, "　この拷問はね、とてもシンプル。",
		   NULL, " This method of torture is very simple.", Line_WaitForInput);
	OutputLine(NULL, "左手の小指の先端の節に釘を打つ。",
		   NULL, " I'll nail one of these into the joint on the end of your left pinky finger.", Line_WaitForInput);

//「.........梨花ちゃんが、...覚醒剤の常用者だって言うのか...？！￥
// No voice
	OutputLine(NULL, "-「………梨花ちゃんが、…覚醒剤の常用者だって言うのか…？！」",
		   NULL, "\".........Are you trying to tell me... that Rika-chan is a drug addict...?!\"", Line_Normal);

How do you think it? I think this is easier way, and save the good thing of both version.
If administrator confirm this. I'll restore the deleted texts.

**Comment by ItaloKnox** [comment]
Hi,

Onikakushi is actually a very special chapter because it was our first release. We tried to be as close as possible to the console version, so your comment makes a lot of sense. I also agree with you.

As for your suggestion, we can't mark the text in-game for a number of reasons but the biggest one of them is because it wouldn't look good. When we find issues with the script, we detail them in the readme so we can look into them later. If you are not afraid of spoilers, [see this](https://github.com/07th-mod/meakashi/blob/2cb0c872dcde202f2e6d7d1a9489bed3236fcc13/README.md#known-issues-for-fixing).

Our stance about censorship changed a lot since our first release, so after Watanagashi we stopped changing the script when the censorship was too substantial. Minor changes are acceptable, but anything that would change the meaning of the text or tone down the story is usually not added. In this case, we now prefer to make a scene unvoiced instead of voicing the censored version.

I hope that makes you satisfied and clear any doubts about how we handle these releases.

**Comment by P-Chang** [comment]
Thank you for reading my snooty and broken long comment.
What a shame, I really skip the knownissue because I watched it on web only, sorry for that.

And I'm bit returd in English. Can I edit the edited script line? 
My dictionary says that agree and confirm is same.

Please say, "Yes, you can" or "No, you can't"

**Comment by ItaloKnox** [comment]
To be short, no you can't. But there's a reason for that.

Since Onikakushi is already a stable release, we won't touch the scripts before we finish the complete Higurashi series. When I said that I agreed with you, I meant that censoring the text was far less than ideal.

The issue with changing Onikakushi (chapter 1) while we are already preparing for ‎Tsumihoroboshi (chapter 6) is that every change needs to be extensively tested, and we've been really busy lately preparing the transition to the [ADV mode](https://github.com/07th-mod/guide/wiki/ADV-Mode).

I promise to go back to Onikakushi as soon as we finish everything, but for now we can't change anything. Really sorry about that but I appreciate your will to make it better.

**Comment by P-Chang** [comment]
OK. Thank you for response　and sorry for waste your time.

**Comment by ItaloKnox** [comment]
Don't worry about that, you raised a very important point so we can work on that when we have time. 👍
