### ISSUE TITLE
ADV Mode did not work for me 

### ISSUE THREAD

**Issue by yagamisempai** [07th-mod/onikakushi#87]
![sin titulo](https://user-images.githubusercontent.com/28794338/28589398-45dceeca-717e-11e7-8332-b9e4d0e9db10.png)

Watanagashi and tatari goroshi worked just fine but i had this problem only on onikakushi

**Comment by enumag** [comment]
It seems the patch is not installed correctly. Either you have wrong scripts in the Update directory or they are not compiled for some reason which can be fixed by deleting everything in the CompiledUpdateScripts directory. Or you have a very very old version of Onikakushi and need to update it first.
