### ISSUE TITLE
Possbile TIPS upgrade?

### ISSUE THREAD

**Issue by temp-user527** [07th-mod/onikakushi#98]
Some user in the comments section of the Steam Community Guides for Chapter 1 made a post regarding replacing sprites and backgrounds in the TIPS section of the game. 
Thread: http://steamcommunity.com/sharedfiles/filedetails/?id=969638685
Comment: https://i.imgur.com/H2EZGDB.png
Here's is the image he posted: http://steamcommunity.com/sharedfiles/filedetails/?id=969638685

The post is dated July of 2017 so I guess it's possible that body else knew about it. Is this something you guys would be interested in adding to the patch? I'll see if I can get more info about how to do it and share it here in any case.

**Comment by enumag** [comment]
@P-Chang actually made some progress about this as well but he couldn't figure out how to make it work with 16:9 aspect ratio.

See https://github.com/07th-mod/higurashi-patch-compiler/issues/5.

**Comment by enumag** [comment]
@P-Chang Let's say we just want to replace the small preview images for the tips. Can you already do that?

**Comment by P-Chang** [comment]
@enumag 
If someone prepare image, replacing can do too much easily.

**Comment by enumag** [comment]
@P-Chang Can you give us some info about what the images should look like? What are the dimensions supposed to be? Should the dark border/shadow be part of the images or is it applied automatically?

**Comment by P-Chang** [comment]
![tipsprefab-sharedassets0 assets-24](https://user-images.githubusercontent.com/29869319/34558427-74731218-f181-11e7-92aa-41a07443f081.png)

Probably you can know how it work with seeing image data.
I have no idea for explain in comment.

**Comment by enumag** [comment]
Thanks. I'll first try contacting that Nozoki guy on steam - I assume he has an updated version of this already.

**Comment by enumag** [comment]
Hmm do you guys know how to contact someone on steam? I can't find any private messages and can't write to his public profile either.

**Comment by ItaloKnox** [comment]
The only way is to add him as a friend and message him directly.

**Comment by enumag** [comment]
Well I did that but I'm not sure if he'll accept a friendship request from a stranger. And it was not possible to add a text note to the request.

**Comment by Nozoki17** [comment]
Well, hello, Nozoki here, one of you actually pointed me to this thread to get my files for the tips images, I don't have the files on this specific computer, but I already have an Onikakushi ready with both Steam and PS2 sprites and backgrounds. I'll make sure to drop them here as soon as possible, and if needed, I can really easily make the same for chapter 2, 3 and 4 (and 5 if someone gives me the image)

**Comment by enumag** [comment]
@Nozoki17 Thanks for stopping by. We'd really appriciate the images for other chapters as well. @P-Chang should be able to extract the Meakashi one for you.

The background is kind of a struggle for us at the moment (see https://github.com/07th-mod/higurashi-patch-compiler/issues/5). You can drop it here for us to try but I can't say for sure if we will be able to use it.

Do you have any other improvements we could use? Also I understand you're working on a translation - what language is that? I assume you're using our patches as a base?

**Comment by P-Chang** [comment]
Here
![tipsprefab](https://user-images.githubusercontent.com/29869319/34604750-571d0f18-f24c-11e7-85f7-95aa7566bbed.png)

What a boring tips texture ever lol

**Comment by Nozoki17** [comment]
![tipsprefab1](https://user-images.githubusercontent.com/35120334/34604864-a69ae3a0-f209-11e7-8766-935bb098bb88.png)
![tipsback](https://user-images.githubusercontent.com/35120334/34604873-ad14aa68-f209-11e7-83a9-6cc7eedad608.png)

Thanks for the image, I'll see what I can do with the assets I already have.

As for the improvements I can bring, not much, I was just translating all the menu items in photoshop.. but if you do need help with modifying some of those, I'm quite good with photoshop. 

I was also thinking about doing something about all those ugly blue menus, maybe giving them a black and red treatment to make them closer to the PS2 version.

And finally, for my translation project (Translating to french), yes I was using your patches as a base (I hope it's okay?) but I'm working on it in my spare time and on my own so it goes very slowly..

**Comment by P-Chang** [comment]
Thanks
http://www.mediafire.com/file/wpuikrzudbtropb/onikakushi_tips.exe

I tested UABE tool Installer, It completely works.
But I don't know why Mediafire detect it as virus... (checking with MSE is fine)

**Comment by enumag** [comment]
@P-Chang What is that exe file for?

@Nozoki17 Thanks for the image for Onikakushi! @P-Chang should be able to put that in. As for some GUI replacements we have no such plans right now but it might get on the list when we finish the changes we're currently working on.

We recently had someone called vonmalvarius on our Discord saying he is also working on a french translation. Is that you or are you guys working together? If not you might want to join your efforts with him.

Using our patches as base is completely fine, go right ahead. We'll even gladly link your translation in our readmes and wiki when it's ready. Just beware that it might be difficult to update your translation to a newer version of our patch when we make a large upgrade (one such upgrade - lip-sync - is actually coming soon). I might be able to help with the upgrade to some extent when needed.

Better sound effects might be nice. When you have something to show, please create a new issue and we'll gladly check it out. And if you have any other ideas for improvement, please share. We're slowly running out of things to do. :-D

**Comment by Nozoki17** [comment]
I'm working on the Tips images for the other 4 chapters, should I upload them here or is there a more appropriate place?

**Comment by enumag** [comment]
Here is fine. And take your time, there is no need to rush. Thanks for doing it. :-)

**Comment by Nozoki17** [comment]
![tipsprefabwata](https://user-images.githubusercontent.com/35120334/34615404-0fc32c90-f235-11e7-849c-c9585ba40e81.png)

Here's the one for Watanagashi-Hen, the other ones will have to wait a bit sadly, I'm really busy at the moment.

**Comment by Nozoki17** [comment]
![tipsprefabwata](https://user-images.githubusercontent.com/35120334/34615773-4e673f1c-f236-11e7-818c-5c828be4cd25.png)

Here's the tips for Watanagashi-Hen, I'll do the rest later because it get's boring very quickly xD But I'll do them nonetheless

**Comment by enumag** [comment]
@Nozoki17 Great work! We're only missing Hima and Mea now, right?

**Comment by Nozoki17** [comment]
Yep, Hima will take a bit of time because of its size and edits I need to make, but Meakashi should be quite quick

**Comment by enumag** [comment]
Huh? Wasn't Hima the shortest chapter? Well I guess you know better than me in the context of this issue. ^^

**Comment by Nozoki17** [comment]
It may be shorter, but the tips file is almost twice as big as Tata, I was very surprised aswell

**Comment by enumag** [comment]
@P-Chang We're slowly approaching a pre-release stage. Can you take the updated tips image for Onikakushi, hack it into the game files and upload what is needed to be replaced? Don't care about other chapters for now. No rush of course. It'll take at least a weak or two before the other things are ready. Just letting you know what's needed.

**Comment by P-Chang** [comment]
It's really easy thing in I'm working.

@Nozoki17 
Tips UI Icon are these
![34558427-74731218-f181-11e7-92aa-41a07443f081](https://user-images.githubusercontent.com/29869319/35012822-7c5d4210-fb4e-11e7-8b34-8c8ec7b6a657.png)

**Comment by Nozoki17** [comment]
Are these what? :3 Sorry I don't make a lot of progress nor have a lot of time to report right now, I'm on an exam week, should be better for friday. I can still make a fix or two to what I already did

**Comment by P-Chang** [comment]
Didn't you say about Tips button improving?
I put a number. and there are no need to hurry.

![34558427-74731218-f181-11e7-92aa-41a07443f081](https://user-images.githubusercontent.com/29869319/35013652-688c6a38-fb51-11e7-86ac-3d5a8b933c5a.png)
![20180117063450_1](https://user-images.githubusercontent.com/29869319/35013501-fbfba8f2-fb50-11e7-9eee-1236dad0cc34.jpg)
![20180117063501_1](https://user-images.githubusercontent.com/29869319/35013506-fd14d6e6-fb50-11e7-8baa-1f3adb592ea3.jpg)

**Comment by Nozoki17** [comment]
Oh god I feel stupid, number 1 on the tips might be the thing I've been looking for for ages. Number 2 is fine as it is I think, and number 3 depends of if we really do switch the UI to something a bit more modern. I could maybe try to at least make them similar to the other buttons, because those are really ugly right now

**Comment by enumag** [comment]
If you change color of number 1 then maybe you should also change number 2 for consistency? And number 3 felt out of place since the beginning so it would be nice to have that changed according to new UI as well.

**Comment by InochiPM** [comment]
I don't know if were still working on this or whats happening but, may i make a suggestion for the buttons? 

You could make them look like the menu buttons from the main menu, rounded and black with the white stroke. 

Like this 
![menu_tips1-test](https://user-images.githubusercontent.com/13459080/35601875-3bd555ba-0603-11e8-8ad3-4717a5a14b06.png)

Also how about putting the Tips Menu icon on the BG so that way when the menu loads it shows it in the top right corner like this? 
![bg_tips-test](https://user-images.githubusercontent.com/13459080/35601898-5ba059c6-0603-11e8-8c58-88b72c76035b.png)

**Comment by enumag** [comment]
@InochiPM Not sure if it's possible to get such button working. cc @P-Chang 

@Nozoki17 What do you think?

**Comment by enumag** [comment]
@InochiPM Sadly 16:9 is a problem here. By the way the status of this is that Nozoki kind of stopped responding like two weeks ago. I think we should give him some more time and if he doesn't show up, someone else should take over. We still want to add both this and the new UI into the game.

**Comment by InochiPM** [comment]
@enumag I may not know about any of the hacking and such, but like Nozoki im good with photoshop since im a graphic designer by trade. So if we need somethings updated or the look of things edited in photoshop i can change colors and make buttons and such. But we should wait first to see if they come back.

**Comment by enumag** [comment]
@InochiPM The hacking is mainly done by @P-Chang anyway so we only need someone like you with photoshop skills. @Nozoki just [posted](https://github.com/07th-mod/higurashi-patch-compiler/issues/22#issuecomment-362185012) in another issue that he is really busy now. So If you want to finish what he started here and in #99, go right ahead.

**Comment by P-Chang** [comment]
![1](https://user-images.githubusercontent.com/29869319/35676995-4b35fcc8-0791-11e8-982e-1a91d6fc5e0f.png)
It works fine. but I think adding square frame may make it more good.
EXIT button is fine. however if you'll make another button, i want to look it.

![2](https://user-images.githubusercontent.com/29869319/35677155-dfc3ac5a-0791-11e8-9442-e5f4f4aa255e.png)
Extra menu is really terrible. If we can add effect in this, it may good. but It may be hardcoded in Assets binary. I can only swapping texture in those files.

**Comment by temp-user527** [comment]
Yikes! That looks really dark,
My suggestion would be to make the buttons should start as subdued red color, then have it light up and glow when you activate it.

**Comment by InochiPM** [comment]
@P-Chang I take it the extras menu has that really nasty glow on it from the text button? Also I don’t know what you mean by square frame for the arrows, sorry. 

I’ll test out the red fade on the buttons for the extras menu and post it here in a while, but I wanted to see the BG I posted tested out as the BG for the tips menu to see if we could have the tips menu icon in there or not.

**Comment by InochiPM** [comment]
@enumag @P-Chang I’m gonna need all of the menu assets and such if I’m going to be able to edit them for the patch

**Comment by enumag** [comment]
Right. @P-Chang Could you extract all images from the assets file? Just Onikakushi is enough for now I think.

**Comment by P-Chang** [comment]
http://www.mediafire.com/file/xnp90n4a7fbcr3i/ch1_AssetTexture.rar
here

**Comment by InochiPM** [comment]
@P-Chang Awesome! Ill get to work on them tonight and i should have them done by friday night.
I'll pass any changed i make by you guys here or on discord. 

Also, the font files included in the assets might actually be where the glowing comes from, but it also is sampled in the game engine for the in game text probably? So idk but the two font atlas files have a precise glow on them all.

**Comment by InochiPM** [comment]
![menu_oni-tips1-test-2](https://user-images.githubusercontent.com/13459080/35709211-91cc61b6-077f-11e8-8e62-91917fcdec16.png)
Heres the Tips, with the diffrent menu button with the added red in the center. 
I also gave the arrows a drop shadow and changed the logo to the hou logo.

**Comment by Nozoki17** [comment]
That looks awesome, exactly what I had in mind! Sorry for the dissapearance btw, lot of health issue atm, I'll try to get back to work asap, i'm really sorry..

**Comment by jwgrlrrajn** [comment]
Not that it's a big deal, but is there a particular reason the PS3 Rena is zoomed in on, but the MG Rena is regular size?

**Comment by Nozoki17** [comment]
It was like that on the original too, so I just followed it..

**Comment by InochiPM** [comment]
@Nozoki17 No problem! You just take all the time you need to get over your health issues no ones rushing you ^^!

**Comment by P-Chang** [comment]
it shouldn't be Hou, I think.

Anyway I don't know how font work. In the fact, game work on 3D, so all font may be mesh. font tweak is probably hard.

**Comment by InochiPM** [comment]
@P-Chang Want me to revert it back to the vanila logo? I got the Sui logo i made, along with the vanila logo.

**Comment by P-Chang** [comment]
Yep, vanilla one. QA should be normal, AA should be Kai.

**Comment by P-Chang** [comment]
![3](https://user-images.githubusercontent.com/29869319/35710044-a10d40e0-07f8-11e8-83ba-51d5b92ca03d.png)

In game, it is bit strange because text was used by engine. using only gradation make it better I think.

**Comment by InochiPM** [comment]
![menu_tips1-test-2](https://user-images.githubusercontent.com/13459080/35710393-31227688-0785-11e8-81f2-0f402bc46f2a.png)
There i change the logo back to vanila.

**Comment by InochiPM** [comment]
Aha! I understand now, So the SDF files are used in the engine to create sharper and nicer text using the render system in unity. So the Font files are used for the Text in the game and when the resolution is raised the font quality goes up with so it doesn't get pixelated and gross. So apart of the engine that renders the text is what needs to be edited, and that would probably be hard coded since its in the engine itself.

**Comment by InochiPM** [comment]
![backlog_button](https://user-images.githubusercontent.com/13459080/35713185-f0f62ea6-0793-11e8-9295-6849eaba00eb.png)

Hows this for the Backlog button, it took a bit of figuring out what the button did, and i made them look like the main menu buttons.

**Comment by InochiPM** [comment]
![mainui_1](https://user-images.githubusercontent.com/13459080/35714293-c914b5aa-0799-11e8-817f-841d971f93c3.png) And how is this for the Main UI look, i like the look of @Nozoki17 's original re-color but added the buttons to look more like the ui buttons i made.

**Comment by P-Chang** [comment]
I think you are hold by making Sui like UI.
It will break coherence. we have too much limitation in UI edit.

If we touch Main UI, we need convert all.

Main UI is not so bad. we need to more look in EXTRA menu UI, I think.

**Comment by InochiPM** [comment]
[Higu_ONI.zip](https://github.com/07th-mod/onikakushi/files/1688480/Higu_ONI.zip)
Im going to go ahead and upload what i have done in this zip file, i still have some of the menu boxes and buttons to change but ill get around to those tomorrow @P-Chang Tell me if anything is broken or misaligned and ill fix it. 

I also included the updated splash screens i did, as-well as the smaller logo versions and the no_data file for the game.

**Comment by InochiPM** [comment]
@P-Chang Yeah, im more or less trying to make it look more like Sui & Matsuri since they both have the same theme to them While also maintaining the higurahsi theme that they used on the main menu buttons as well since thats what the PS2 & PS3 games buttons and themes are based off of lol, The blockiness of the Main UI is really incoherent with the buttons styled for the main menu so i played around with the theme a bit, while also keeping the original files with their edited colors.

**Comment by InochiPM** [comment]
@P-Chang I’m almost done with the editing, I just have a few more I need to edit and I’ll send the full zip file, the updated UI I made has some translation fixes and some better wording for the English. In the end if my UI isn’t used for the final push through it could always be put in as an extra download, a UI patch if we could do that. Since I think we’re only limited to the text on the UI since it’s read directly from the SDF file and placed, but the buttons and such with wording are easily replaceable I would think.

Also I would like to know which buttons in the save menu asset are used on the Japanese side since mangagamer didn’t use Japanese’s for the words “save” & “load”, cause I’m not to sure but the one Japanese button for the save menu is delete.

**Comment by InochiPM** [comment]
Okay im all done now! @enumag @P-Chang @Nozoki17 Take a look, hopefully its alright since it took a lot longer to re-color the menus and make my own lmao. 

[Higu_ONI-UI.zip](https://github.com/07th-mod/onikakushi/files/1692558/Higu_ONI-UI.zip)

Its quite a hefty file since its got all of the changes inside of it, in the zip is

- **New_Splash Folder** : In this folder i included the two splash screens i made, the first being 07th Expansion with the manga gamer logo in the top left corner and KAGA Create logo in the top right since were using the Sui Assets. Then a second splash named mangagamer.png and its a disclaimer splash using the assets from sui because it had its own disclaimer so i made one special for this patch. 

- **Smaller_Logo Folder** : Included this since i thought the logos were just way to big on the opening screen like @Nozoki17 did with their logo changes, making them much smaller so it didn't feel like the whole screen was being used up by the logos. 

- **Re-color_UI Folder** : Just the re-colored version of the regular UI, the color is changed to red, and since MangaGamer decided to not use the same color for all of the menus, so some of the colors might be off by a bit and not red red. 

- **New_UI Folder** : This is my personal take on the Higurashi style with the UI, since the main UI isnt that great i wanted something more like Matsuri & Sui but with my own twists. Now i know its something really different from the actual UI but it should work, and in the event it doesn't get put in, we can always make it a Patch for a better UI or a more Matsuri/Sui Like UI. 

And last i made an edit of the no_data.png file since it was really plain and boring so i threw the higu logo on it.

**Comment by enumag** [comment]
@InochiPM Wow, very nice! I like the New_UI though I want to see it in game to be sure. Could you hack that in @P-Chang?

**Comment by InochiPM** [comment]
@enumag it took a while of editing and thinking to figure out what would look nice with the backgrounds and such. I’m hoping it works because I kept everything within bounds of the UI so nothing should be broken.

**Comment by InochiPM** [comment]
Oh yeah! I forgot to mention, I fixed the higu background with the logo in the bottom so it’s all HD as well as the black background I added a version with the cicadas on it and the other without them lol

**Comment by InochiPM** [comment]
@enumag So while playing through Sui, I found the Tips menu music in the sui files and i was wondering if we could import that as the tips music instead of the music that plays during the tips menu?  It's hm11_85.ogg i also found the mainmenu theme as well its hm11_82.ogg

**Comment by enumag** [comment]
@InochiPM Create a new issue for the music thing so that we don't forget it. But it's a rather low priority fow now which you can probably understand.

The bigger problem here is that as far as I know P-Chang was the only one who knew how to pull images from the assets file and how to put edited images back in. I don't even know what tools he used. Any ideas? (@Nozoki17 might know)
